spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/binfudexercise
    username: postgres
    password: 90opklnm
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1080555922887-qoumuctll5jnlp3i3pn6u12us9n84t1o.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub