spring:
  application:
    name: binfood-gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: user_service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/user/**
#        - id: order_service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/order/**